# Generated by Django 3.1.1 on 2020-09-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200919_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, upload_to='book_images'),
        ),
    ]
