# Generated by Django 3.1.1 on 2020-09-21 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_books_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=100)),
                ('card_no', models.IntegerField()),
            ],
        ),
    ]
