# Generated by Django 3.1.1 on 2020-09-22 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='likes',
            field=models.ManyToManyField(related_name='book_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
