# Generated by Django 3.1.1 on 2020-09-23 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20200922_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
