# Generated by Django 3.1.1 on 2020-09-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_books_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
