# Generated by Django 3.1.1 on 2020-09-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200927_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
