# Generated by Django 3.1.1 on 2020-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_books_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='comments',
            field=models.TextField(blank=True, help_text='Write your comment here'),
        ),
    ]
