# Generated by Django 3.1.1 on 2020-09-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200930_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='book',
        ),
        migrations.RemoveField(
            model_name='books',
            name='com',
        ),
        migrations.AddField(
            model_name='books',
            name='com',
            field=models.ManyToManyField(blank=True, related_name='book_comment', to='main.Comments'),
        ),
    ]
