# Generated by Django 3.1.1 on 2020-09-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200930_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='book',
        ),
        migrations.AddField(
            model_name='comments',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='book_comment', to='main.Books'),
        ),
    ]
