# Generated by Django 3.1.1 on 2020-09-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200930_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='book',
        ),
        migrations.AddField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='main.books'),
        ),
    ]
