# Generated by Django 3.1.1 on 2020-10-04 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200930_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsReplys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, help_text='Write your comment here')),
                ('date_replied', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='main.comments')),
            ],
        ),
    ]
