# Generated by Django 3.1.1 on 2020-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_commentsreplys'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
