# Generated by Django 3.1.1 on 2020-10-05 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_commentsreplys_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentsreplys',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comments_reply_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
